# Generated by Django 4.0.5 on 2022-07-05 06:26

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, verbose_name='Sektor raqami')),
                ('shaxs', models.CharField(max_length=150, verbose_name="Sektorga bog'langan shaxs")),
                ('name', models.CharField(max_length=100, verbose_name='MFY nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('familya', models.CharField(max_length=100, verbose_name='Familya')),
                ('sharif', models.CharField(max_length=100, verbose_name='Sharif')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ism')),
                ('tsana', models.DateField(verbose_name="Tug'ilgan sana")),
                ('jins', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=20, verbose_name='Jinsi')),
                ('passport', models.CharField(max_length=15, verbose_name='Passport raqami')),
                ('jshir', models.PositiveIntegerField(blank=True, null=True, verbose_name='JSHIR')),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon raqam 2')),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon raqam 1')),
                ('manzil', models.CharField(blank=True, max_length=200, null=True, verbose_name='Manzil')),
                ('kochib_ketgan', models.BooleanField(blank=True, default=False, null=True, verbose_name="Boshqa hududga ko'chib ketgan")),
                ('vafot_etgan', models.BooleanField(blank=True, default=False, null=True, verbose_name='Vafot etgan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tekshirildi', models.BooleanField(default=False, verbose_name='Tekshirilganlik holati')),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_cr', to='accounts.myuser')),
                ('mfy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_mfy', to='persons.mfy', verbose_name='MFY')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='persons.person', verbose_name="Oila boshlig'i")),
            ],
        ),
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ish beruvchi tashkilot')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('stir', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tashkilot STIR raqami')),
                ('loyiha', models.PositiveIntegerField(verbose_name='Tashkilot loyihalari soni')),
                ('ish_orni', models.PositiveIntegerField(verbose_name="Tashkilot yaratgan ish o'rni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Viloyat nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Yordam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='person')),
                ('yordam_sanasi', models.DateTimeField(auto_now_add=True)),
                ('vakil_fio', models.CharField(blank=True, max_length=100, null=True)),
                ('yuridik', models.BooleanField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon raqam')),
                ('yordam_turi', models.CharField(choices=[('oziq_ovqat', 'Oziq-ovqat mahsulotlari etkazib berish'), ('naqt_pul', "Naqt (yoki plastik kartochka) pul ko'rinishida"), ('komunal_tolandi', "Komunal qarzi to'lab berildi(gaz, suv svet"), ('dori_darmon', 'Dori darmon yetkazib berildi'), ('boshqa_yordam', "Ko'rsatilgan boshqa yordam"), ('qoramol', 'Chorva: qoramol'), ('qoy', "Chorva: qo'y"), ('echki', 'Chorva: echki'), ('parranda', 'Chorva: parranda'), ('quyon', 'Chorva: quyon'), ('asalari', 'Chorva: asalari'), ('pf_6038', 'PF-6038 (30.07.2020)'), ('vmf_346', 'VMF-346 (29.07.2020)'), ('pq_5204', 'PQ-5204 (30.07.2021)'), ('pq_4815', 'PQ-4817 (26.08.2021)')], max_length=250, verbose_name='Yordam turi')),
                ('summa', models.PositiveIntegerField(blank=True, null=True, verbose_name='Yordam summasi')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tekshirildi', models.BooleanField(default=False, verbose_name='Tekshirilganlik holati')),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yordam_cr', to='accounts.myuser')),
                ('korxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yordam_korxona', to='persons.tashkilot', verbose_name='Korxona nomi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yordam_person', to='persons.person')),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sektor', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=50, verbose_name='Viloyat sektori')),
                ('shaxs', models.CharField(max_length=150, verbose_name="Sektorga bog'langan shaxs")),
                ('name', models.CharField(max_length=50, verbose_name='Tuman nomi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuman_viloyat', to='persons.viloyat', verbose_name='Viloyat nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Tash_Faoliyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faoliyat_turi', models.CharField(choices=[('oilaviy_tadbirkorlik', 'Oilaviy tadbirkorlik'), ('xunarmandchilik', 'Xunarmandchilik'), ('jamoat_ishlari', 'Jamoat ishlari'), ('sanoat_loyhalari', 'Sanoat loyihalari'), ('agrosanoat_loyihalari', 'Agrosanoat loyihalari'), ('kooperatsiya_asosida', 'Kooperatsiya asosida yer ajratish'), ('takroriy_ekin', 'Takroriy ekin'), ('qurilishda_ishlash', 'Qurilish obyektlarid ishlash'), ('rasmiy_ozi_band_qilish', "Rasmiy o'zini o'zi band qilish(PQ-4742)"), ('norasmiy_bandlik', 'Norasmiy bandlik(odam va yuk tashish xizmati, shaxsiy qurilishda quruvchi va h.k)'), ('ishiga_qaytish', "O'zining ishiga qaytish(karantin yumshatilishi)"), ('boshqa_ft', 'Boshqa faoliyat turlari')], max_length=200, verbose_name='korxona faoliyat turi')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='faoliyat_turi')),
                ('loyiha', models.PositiveIntegerField(verbose_name="Faoliyat bo'yicha yaratilgan loyihalar soni")),
                ('ish_orni', models.PositiveIntegerField(verbose_name="Faoliyat bo'yicha yaratilgan ish o'rinlari soni")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tashkilot_cr', to='accounts.myuser', verbose_name='Malumot kirituvchi')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tashkilot_faoliyat', to='persons.tashkilot')),
            ],
        ),
        migrations.CreateModel(
            name='Qaror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='person')),
                ('qaror_raqami', models.CharField(max_length=30, verbose_name='Qaror raqami')),
                ('qaror_sanasi', models.DateField(verbose_name='Qaror sanasi')),
                ('qaror_fayli', models.FileField(upload_to='qaror_fayli/%Y/%m/%d/', verbose_name='Qaror fayli')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaror_cr', to='accounts.myuser', verbose_name='Malumot kirituvchi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaror_person', to='persons.person')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='person')),
                ('photo', models.ImageField(upload_to='yordam_rasmi/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_person', to='persons.person')),
            ],
        ),
        migrations.AddField(
            model_name='mfy',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfy_tuman', to='persons.tuman', verbose_name='Tuman nomi'),
        ),
        migrations.CreateModel(
            name='Ishsiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='person')),
                ('faoliyat_turi', models.CharField(choices=[('oilaviy_tadbirkorlik', 'Oilaviy tadbirkorlik'), ('xunarmandchilik', 'Xunarmandchilik'), ('jamoat_ishlari', 'Jamoat ishlari'), ('sanoat_loyhalari', 'Sanoat loyihalari'), ('agrosanoat_loyihalari', 'Agrosanoat loyihalari'), ('kooperatsiya_asosida', 'Kooperatsiya asosida yer ajratish'), ('takroriy_ekin', 'Takroriy ekin'), ('qurilishda_ishlash', 'Qurilish obyektlarid ishlash'), ('rasmiy_ozi_band_qilish', "Rasmiy o'zini o'zi band qilish(PQ-4742)"), ('norasmiy_bandlik', 'Norasmiy bandlik(odam va yuk tashish xizmati, shaxsiy qurilishda quruvchi va h.k)'), ('ishiga_qaytish', "O'zining ishiga qaytish(karantin yumshatilishi)"), ('boshqa_ft', 'Boshqa faoliyat turlari')], max_length=200, verbose_name='Ishlash istagidagi faoliy turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishsiz_cr', to='accounts.myuser', verbose_name='Malumot kirituvchi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishsiz_person', to='persons.person', verbose_name='mehnatga layoqatli ishsiz shaxs')),
            ],
        ),
        migrations.CreateModel(
            name='Ishli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='person')),
                ('faoliyat_turi', models.CharField(choices=[('oilaviy_tadbirkorlik', 'Oilaviy tadbirkorlik'), ('xunarmandchilik', 'Xunarmandchilik'), ('jamoat_ishlari', 'Jamoat ishlari'), ('sanoat_loyhalari', 'Sanoat loyihalari'), ('agrosanoat_loyihalari', 'Agrosanoat loyihalari'), ('kooperatsiya_asosida', 'Kooperatsiya asosida yer ajratish'), ('takroriy_ekin', 'Takroriy ekin'), ('qurilishda_ishlash', 'Qurilish obyektlarid ishlash'), ('rasmiy_ozi_band_qilish', "Rasmiy o'zini o'zi band qilish(PQ-4742)"), ('norasmiy_bandlik', 'Norasmiy bandlik(odam va yuk tashish xizmati, shaxsiy qurilishda quruvchi va h.k)'), ('ishiga_qaytish', "O'zining ishiga qaytish(karantin yumshatilishi)"), ('boshqa_ft', 'Boshqa faoliyat turlari')], max_length=200, verbose_name='korxona faoliyat turi')),
                ('sana', models.DateField(verbose_name='Ishga joylashgan sana')),
                ('band_qilish', models.CharField(blank=True, max_length=200, null=True, verbose_name="O'zini o'zi band qilish turi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishli_cr', to='accounts.myuser', verbose_name='Malumot kirituvchi')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishli_person', to='persons.person', verbose_name='Ishga Joylashtirilgan shaxs')),
                ('tashkilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ishli_tashkilot', to='persons.tashkilot', verbose_name='Ish beruvchi tashkilot')),
            ],
        ),
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='person')),
                ('fayl', models.FileField(upload_to='yordam_fayli/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fayl_person', to='persons.person')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='parent')),
                ('toifa', models.CharField(choices=[('muhtoj_oila', 'Muhtoj oila'), ('band_oila', 'Bandligi taminlangan oila'), ('muhtoj_emas_oila', "Muhtojlar ro'yhatidan chiqarilgan")], max_length=20, verbose_name='Toifa')),
                ('oila_azolari_soni', models.PositiveIntegerField(verbose_name='Oila azolari soni')),
                ('ishsizlar_soni', models.PositiveIntegerField(verbose_name='Mehnatga layoqatli ishsizlar')),
                ('ijtimoiy_holat', models.CharField(choices=[('ogir_kasal', "Og'ir kasal"), ('farzandi_bor_oila', '5 va undan ortiq farzandi bor oila'), ('boquvchisini_yoqotgan', "Boquvchisini yo'qotgan(beva ayollar)"), ('boshqalar', 'Boshqalar'), ('cheteldagi_daromadlari', 'Chet eldagi daromadlari'), ('uzdagi_daromadlari', "O'zbekistondagi daromadlari"), ('kam_taminlangan', 'Kam taminlangan(VMQ-44)'), ('nogiron', 'Nogiron'), ('yakka_yolgiz', "Yakka yolg'iz(Keksalar)")], max_length=100, verbose_name='Ijtimoi holati')),
                ('oila_guruhi', models.CharField(choices=[('juda_muhtoj', "O'ta muhtoj oila"), ('muhtoj', 'Muhtoj oila'), ('vaqtincha_muhtoj', 'Vaqtincha muhtoj oila')], max_length=100, verbose_name='Ehtiyojmant oila guruhi')),
                ('guruh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Guruh')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Oila telefon raqami ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famly_cr', to='accounts.myuser')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_parent', to='persons.person')),
            ],
        ),
    ]
