# Generated by Django 4.0.5 on 2022-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='bandlar_soni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='bandligi taminlangan oila azolari'),
        ),
        migrations.AlterField(
            model_name='family',
            name='ishsizlar_soni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Mehnatga layoqatli ishsizlar'),
        ),
    ]
