# Generated by Django 4.0.5 on 2022-07-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_family_vafot_etgan_soni_alter_family_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='vafot_etgan_soni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vafot etkanlar soni'),
        ),
        migrations.AlterField(
            model_name='mfy',
            name='sektor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='Sektor raqami'),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='sektor',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=50, verbose_name='Viloyat sektori'),
        ),
    ]
