# Generated by Django 4.0.5 on 2022-07-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_family_vafot_etgan_soni_alter_mfy_sektor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kompleks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Kompleksga bog'langan shaxs")),
                ('status', models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv'), ('delete', 'Delete')], default='active', max_length=20, verbose_name='Holati')),
            ],
        ),
    ]
