# Generated by Django 4.0.5 on 2022-07-23 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('persons', '0005_kompleks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashkilot',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tashkilot_cr', to='accounts.myuser', verbose_name='Malumot kirituvchi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tashkilot',
            name='faoliyat_turi',
            field=models.CharField(choices=[('oilaviy_tadbirkorlik', 'Oilaviy tadbirkorlik'), ('xunarmandchilik', 'Xunarmandchilik'), ('jamoat_ishlari', 'Jamoat ishlari'), ('sanoat_loyhalari', 'Sanoat loyihalari'), ('agrosanoat_loyihalari', 'Agrosanoat loyihalari'), ('kooperatsiya_asosida', 'Kooperatsiya asosida yer ajratish'), ('takroriy_ekin', 'Takroriy ekin'), ('qurilishda_ishlash', 'Qurilish obyektlarid ishlash'), ('rasmiy_ozi_band_qilish', "Rasmiy o'zini o'zi band qilish(PQ-4742)"), ('norasmiy_bandlik', 'Norasmiy bandlik(odam va yuk tashish xizmati, shaxsiy qurilishda quruvchi va h.k)'), ('ishiga_qaytish', "O'zining ishiga qaytish(karantin yumshatilishi)"), ('boshqa_ft', 'Boshqa faoliyat turlari')], default=1, max_length=200, verbose_name='korxona faoliyat turi'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tash_Faoliyat',
        ),
    ]
