# Generated by Django 4.0.5 on 2022-07-29 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_alter_tashkilot_ish_orni_alter_tashkilot_loyiha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tashkilot',
            name='mfy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tashkilot_mfy', to='persons.mfy', verbose_name='MFY'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tashkilot',
            name='tuman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tashkilot_mfy', to='persons.tuman', verbose_name='Tuman'),
            preserve_default=False,
        ),
    ]
