# Generated by Django 4.0.5 on 2022-08-09 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0010_yordam_fayl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='famly_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='fayl',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ishli',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishli_cr', to=settings.AUTH_USER_MODEL, verbose_name='Malumot kirituvchi'),
        ),
        migrations.AlterField(
            model_name='ishli',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='ishsiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ishsiz_cr', to=settings.AUTH_USER_MODEL, verbose_name='Malumot kirituvchi'),
        ),
        migrations.AlterField(
            model_name='ishsiz',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='kompleks',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='mfy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='qaror',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qaror_cr', to=settings.AUTH_USER_MODEL, verbose_name='Malumot kirituvchi'),
        ),
        migrations.AlterField(
            model_name='qaror',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='tashkilot',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tashkilot_cr', to=settings.AUTH_USER_MODEL, verbose_name='Malumot kirituvchi'),
        ),
        migrations.AlterField(
            model_name='tashkilot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='viloyat',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='yordam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yordam_cr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yordam',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('arxiv', 'Arxiv')], default='active', max_length=20, verbose_name='Holati'),
        ),
    ]
