# Generated by Django 4.0.5 on 2022-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_alter_family_created_by_alter_family_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ishli',
            name='shartnoma',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shartnoma raqami'),
        ),
        migrations.AddField(
            model_name='qaror',
            name='sabab',
            field=models.TextField(blank=True, null=True),
        ),
    ]
